### ISSUE TITLE
Panic executing: SELECT author_name from commits order by COUNT(*);

### ISSUE THREAD

**Issue by ajnavarro** [sqle/gitql#111]
```
--> Executing query: SELECT author_name from commits order by COUNT(*);

panic: interface conversion: interface is string, not int32

goroutine 1 [running]:
panic(0x9839e0, 0xc420fb87c0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/gitql/gitql/sql.(*integerType).Compare(0xd5d788, 0x949d20, 0xc4201ef910, 0x949d20, 0xc429cec240, 0xc429cec240)
	<autogenerated>:45 +0x82
github.com/gitql/gitql/sql/plan.(*sorter).Less(0xc42811bf20, 0x0, 0x1792, 0x0)
	/home/antonio/work/src/github.com/gitql/gitql/sql/plan/sort.go:156 +0x1e5
sort.medianOfThree(0xcf59c0, 0xc42811bf20, 0x0, 0x1792, 0x2f24)
	/usr/local/go/src/sort/sort.go:74 +0x49
sort.doPivot(0xcf59c0, 0xc42811bf20, 0x0, 0xbc97, 0x53a887, 0xc42006c400)
	/usr/local/go/src/sort/sort.go:99 +0x601
sort.quickSort(0xcf59c0, 0xc42811bf20, 0x0, 0xbc97, 0x1f)
	/usr/local/go/src/sort/sort.go:188 +0x83
sort.Sort(0xcf59c0, 0xc42811bf20)
	/usr/local/go/src/sort/sort.go:222 +0x80
github.com/gitql/gitql/sql/plan.(*sortIter).computeSortedRows(0xc4219fe540, 0x1, 0xb)
	/home/antonio/work/src/github.com/gitql/gitql/sql/plan/sort.go:126 +0x292
github.com/gitql/gitql/sql/plan.(*sortIter).Next(0xc4219fe540, 0xc425fc24d0, 0xc4201ef610, 0xc42030d9e0, 0x4a19fc, 0xc425fc2480)
	/home/antonio/work/src/github.com/gitql/gitql/sql/plan/sort.go:92 +0xd9
github.com/gitql/gitql/sql/plan.(*iter).Next(0xc42571f940, 0xc4201ef600, 0x1, 0x1, 0x0, 0x0)
	/home/antonio/work/src/github.com/gitql/gitql/sql/plan/project.go:65 +0x38
main.(*cmdQueryBase).printQuery(0xc4201d6b40, 0xc42571f960, 0x1, 0x1, 0xcf2700, 0xc42571f940, 0xa34a17, 0x6, 0x0, 0x0)
	/home/antonio/work/src/github.com/gitql/gitql/cmd/gitql/query_base.go:65 +0x222
main.(*CmdShell).Execute(0xc4201d6b40, 0xc4201a96c0, 0x0, 0x1, 0x1, 0x1)
	/home/antonio/work/src/github.com/gitql/gitql/cmd/gitql/shell.go:75 +0xa5a
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc420022a20, 0xc42000c5f0, 0x1, 0x1, 0x4, 0x2, 0xc42001c900, 0xc4200ab080, 0xc4200aaf48)
	/home/antonio/work/src/github.com/jessevdk/go-flags/parser.go:316 +0x8e6
github.com/jessevdk/go-flags.(*Parser).Parse(0xc420022a20, 0xa36250, 0x7, 0xa44624, 0x1d, 0x0)
	/home/antonio/work/src/github.com/jessevdk/go-flags/parser.go:186 +0x74
main.main()
	/home/antonio/work/src/github.com/gitql/gitql/cmd/gitql/main.go:16 +0x38b
```

**Comment by smola** [comment]
Oh, interesting. Note that this is not a valid query, so we should print a valid error.

**Comment by ajnavarro** [comment]
This one is a valid one:

select author_name, count(*) from commits group by author_name order by count(*) desc;

```
--> Executing query: select author_name, count(*) from commits group by author_name order by count(*) desc;

panic: interface conversion: interface is string, not int32

goroutine 1 [running]:
panic(0x9839e0, 0xc4213a8140)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/gitql/gitql/sql.(*integerType).Compare(0xd5d788, 0x949d20, 0xc4237fa230, 0x949d20, 0xc4201adfc0, 0xc4237fa230)
	<autogenerated>:45 +0x82
github.com/gitql/gitql/sql/plan.(*sorter).Less(0xc429c76960, 0x0, 0x1792, 0x0)
	/home/antonio/work/src/github.com/gitql/gitql/sql/plan/sort.go:156 +0x1e5
sort.medianOfThree(0xcf59c0, 0xc429c76960, 0x0, 0x1792, 0x2f24)
	/usr/local/go/src/sort/sort.go:74 +0x49
sort.doPivot(0xcf59c0, 0xc429c76960, 0x0, 0xbc97, 0x53a887, 0xc425014000)
	/usr/local/go/src/sort/sort.go:99 +0x601
sort.quickSort(0xcf59c0, 0xc429c76960, 0x0, 0xbc97, 0x1f)
	/usr/local/go/src/sort/sort.go:188 +0x83
sort.Sort(0xcf59c0, 0xc429c76960)
	/usr/local/go/src/sort/sort.go:222 +0x80
github.com/gitql/gitql/sql/plan.(*sortIter).computeSortedRows(0xc4201d3ac0, 0x1, 0xd5d788)
	/home/antonio/work/src/github.com/gitql/gitql/sql/plan/sort.go:126 +0x292
github.com/gitql/gitql/sql/plan.(*sortIter).Next(0xc4201d3ac0, 0xd5d788, 0x8, 0x1, 0x7fa3d27b14b0, 0x0)
	/home/antonio/work/src/github.com/gitql/gitql/sql/plan/sort.go:92 +0xd9
github.com/gitql/gitql/sql/plan.(*groupByIter).computeRows(0xc4201d3b00, 0x2, 0x2)
	/home/antonio/work/src/github.com/gitql/gitql/sql/plan/group_by.go:110 +0x76
github.com/gitql/gitql/sql/plan.(*groupByIter).Next(0xc4201d3b00, 0xc4201357e0, 0x2, 0x2, 0x0, 0x0)
	/home/antonio/work/src/github.com/gitql/gitql/sql/plan/group_by.go:88 +0xd9
main.(*cmdQueryBase).printQuery(0xc4201d6f00, 0xc4201d3b40, 0x2, 0x2, 0xcf26c0, 0xc4201d3b00, 0xa34a17, 0x6, 0x0, 0x0)
	/home/antonio/work/src/github.com/gitql/gitql/cmd/gitql/query_base.go:65 +0x222
main.(*CmdShell).Execute(0xc4201d6f00, 0xc4201ad6b0, 0x0, 0x1, 0x1, 0x1)
	/home/antonio/work/src/github.com/gitql/gitql/cmd/gitql/shell.go:75 +0xa5a
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc420022ae0, 0xc42000c5f0, 0x1, 0x1, 0x4, 0x2, 0xc42001c7e0, 0xc4200ab080, 0xc4200aaf48)
	/home/antonio/work/src/github.com/jessevdk/go-flags/parser.go:316 +0x8e6
github.com/jessevdk/go-flags.(*Parser).Parse(0xc420022ae0, 0xa36250, 0x7, 0xa44624, 0x1d, 0x0)
	/home/antonio/work/src/github.com/jessevdk/go-flags/parser.go:186 +0x74
main.main()
	/home/antonio/work/src/github.com/gitql/gitql/cmd/gitql/main.go:16 +0x38b
```

**Comment by ajnavarro** [comment]
Migrate to https://github.com/sqle/sqle/issues/5
